apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: v2
  template:
    metadata:
      labels:
        app: api
        version: v2
    spec:
      containers:
      - name: api
        image: api:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: api-v2
spec:
  selector:
      app: api
      version: v2
  ports:
    - protocol: TCP
      port: 4000
  type: ClusterIP
